In [1]:
import numpy as np

## Reshaping and resizing


In [2]:
data = np.array([[1,2],[3,4]])
data


array([[1, 2],
       [3, 4]])

In [3]:
a = np.reshape(data, (1,4))

In [4]:
a

array([[1, 2, 3, 4]])

In [5]:
a.shape

(1, 4)

In [6]:
b = data.reshape(4)
b

array([1, 2, 3, 4])

In [7]:
b.shape

(4,)

In [8]:
data

array([[1, 2],
       [3, 4]])

In [9]:
data_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
data_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
c = data_1.reshape(1,9)

In [11]:
c

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [12]:
data_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
c.shape

(1, 9)

In [14]:
d = data_1.reshape(9)
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
d.shape

(9,)

In [16]:
data

array([[1, 2],
       [3, 4]])

In [17]:
data.flatten()

array([1, 2, 3, 4])

In [18]:
data.flatten().shape

(4,)

In [19]:
data_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
data_1.shape

(3, 3)

In [21]:
data_1.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
data

array([[1, 2],
       [3, 4]])

In [23]:
colu = data[:,np.newaxis] # r,c
colu

array([[[1, 2]],

       [[3, 4]]])

In [24]:
a = np.arange(0,5)
a

array([0, 1, 2, 3, 4])

In [25]:
colu_1 = a[:,np.newaxis]
colu_1

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [26]:
a.shape


(5,)

In [27]:
colu_1.shape

(5, 1)

In [28]:
row = colu_1[np.newaxis,:]
row

array([[[0],
        [1],
        [2],
        [3],
        [4]]])

In [29]:
row.shape

(1, 5, 1)

In [30]:
a # vector


array([0, 1, 2, 3, 4])

In [31]:
a.shape

(5,)

In [32]:
col = a[:,np.newaxis]
col

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [33]:
col.shape

(5, 1)

In [34]:
a

array([0, 1, 2, 3, 4])

In [35]:
row = a[np.newaxis,:]
row

array([[0, 1, 2, 3, 4]])

In [36]:
row.shape

(1, 5)

In [37]:
a

array([0, 1, 2, 3, 4])

In [38]:
np.vstack((a,a,a))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [39]:
np.hstack((a,a,a))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [40]:
a_1 = a[:,np.newaxis]
a_1

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [41]:
np.hstack((a_1,a_1,a_1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

## Sorting

In [42]:
# numeric sort

In [43]:
my_array = np.random.randint(1,20,10)
my_array

array([ 4,  8,  1,  8, 19,  7, 16, 13,  1, 16], dtype=int32)

In [44]:
np.sort(my_array)

array([ 1,  1,  4,  7,  8,  8, 13, 16, 16, 19], dtype=int32)

In [45]:
# text sorting

In [46]:
my_array_1 = np.array(['red','pink','yellow','black','white', 'blue'])
my_array_1

array(['red', 'pink', 'yellow', 'black', 'white', 'blue'], dtype='<U6')

In [47]:
np.sort(my_array_1)

array(['black', 'blue', 'pink', 'red', 'white', 'yellow'], dtype='<U6')

In [48]:
# boolean
my_array_2 = np.array([False, True, True, True, False, False])
my_array_2

array([False,  True,  True,  True, False, False])

In [49]:
np.sort(my_array_2)

array([False, False, False,  True,  True,  True])

In [50]:
A = np.linspace(0,1,11)
A

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [51]:
B = A==0.5

In [52]:
B

array([False, False, False, False, False,  True, False, False, False,
       False, False])

In [53]:
np.sort(B)

array([False, False, False, False, False, False, False, False, False,
       False,  True])

In [54]:
# sorting in 2D
array_1 = np.random.randint(1,20, size=(4,6))
array_1

array([[ 5, 14,  1,  6,  7,  8],
       [10,  4,  7, 19, 19,  4],
       [17,  3,  5, 14,  9,  3],
       [10,  3,  3,  7,  5, 11]], dtype=int32)

In [55]:
np.sort(array_1)

array([[ 1,  5,  6,  7,  8, 14],
       [ 4,  4,  7, 10, 19, 19],
       [ 3,  3,  5,  9, 14, 17],
       [ 3,  3,  5,  7, 10, 11]], dtype=int32)

In [56]:
# descending order

my_array_1 = np.random.randint(1,20,10)
print(my_array_1)

sort_it = np.sort(my_array_1)
final_desc = np.flipud(sort_it)
print(final_desc)

[ 7 13 10 17 19 14 15  8 11  7]
[19 17 15 14 13 11 10  8  7  7]


In [57]:
# broadcasting Numpy
a1 = np.array([14,26,55])
a2 = np.array([10,11,12])
a1+a2


array([24, 37, 67])

In [58]:
a3 = np.array([10])
a1+a3

array([24, 36, 65])

In [59]:
a4 = np.random.randint(1,20, size=(3,4))
a4


array([[14,  6,  6,  6],
       [17, 11,  4, 16],
       [ 8, 14,  5, 10]], dtype=int32)

In [60]:
a5 = np.array([1,1,1,1])
a5

array([1, 1, 1, 1])

In [61]:
a4+a5

array([[15,  7,  7,  7],
       [18, 12,  5, 17],
       [ 9, 15,  6, 11]])

In [62]:
# dot Product


a = np.array([1,2])
b = np.array([3,4])
np.dot(a,b)

np.int64(11)

In [63]:
#1*3 +4*2 = 3 +8 = 11

In [64]:
a1 = np.array([[1,4],[5,6]])
b1 = np.array([[2,4],[5,2]])
np.dot(a1,b1)

array([[22, 12],
       [40, 32]])

In [65]:
# 0,0 => 1*2 +4 * 5 = 22
# 0,1 => 1* 4 + 4 * 2 = 12
# 1,0 => 5 * 2 + 6* 5=40
# 1,1 => 5* 4 + 6 * 2 = 32

In [66]:
a3 = np.array([[3,5],[1,2],[4,1]])
b3 = np.array([2,3])
a3

array([[3, 5],
       [1, 2],
       [4, 1]])

In [67]:
b3

array([2, 3])

In [68]:
np.dot(a3,b3)

array([21,  8, 11])

In [69]:
a3.shape, b3.shape

((3, 2), (2,))

In [70]:
A = np.array([[1,9,2,1,1],
[10,1,2,1,1],
[1,0,5,1,1],
[2,1,1,2,9],
[2,1,2,13,2]])

In [71]:
A

array([[ 1,  9,  2,  1,  1],
       [10,  1,  2,  1,  1],
       [ 1,  0,  5,  1,  1],
       [ 2,  1,  1,  2,  9],
       [ 2,  1,  2, 13,  2]])

In [72]:
from scipy import linalg
B = np.array([170,180,140,180,350]).reshape(5,1)
B

array([[170],
       [180],
       [140],
       [180],
       [350]])

In [73]:
x = linalg.solve(A,B)
x

array([[10.],
       [10.],
       [20.],
       [20.],
       [10.]])